ALTER TABLE task_events ADD COLUMN actor_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE task_events ADD COLUMN actor_kind TEXT NOT NULL DEFAULT '';
ALTER TABLE task_events ADD COLUMN actor_name TEXT NOT NULL DEFAULT '';

ALTER TABLE runs ADD COLUMN actor_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN actor_kind TEXT NOT NULL DEFAULT '';
ALTER TABLE runs ADD COLUMN actor_name TEXT NOT NULL DEFAULT '';
ALTER TABLE runs ADD COLUMN finished_actor_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN finished_actor_kind TEXT NOT NULL DEFAULT '';
ALTER TABLE runs ADD COLUMN finished_actor_name TEXT NOT NULL DEFAULT '';

ALTER TABLE run_artifacts ADD COLUMN actor_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE run_artifacts ADD COLUMN actor_kind TEXT NOT NULL DEFAULT '';
ALTER TABLE run_artifacts ADD COLUMN actor_name TEXT NOT NULL DEFAULT '';
