ALTER TABLE tasks ADD COLUMN source TEXT NOT NULL DEFAULT 'local';
ALTER TABLE tasks ADD COLUMN external_id TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN external_url TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN external_revision TEXT NOT NULL DEFAULT '';
