import { defineConfig } from "@kubb/core";
import { pluginClient } from "@kubb/plugin-client";
import { pluginOas } from "@kubb/plugin-oas";
import { pluginTs } from "@kubb/plugin-ts";

const generatedBanner = "/* This file was generated by Kubb. Do not edit manually. */";

export default defineConfig({
  input: {
    path: "./openapi.json",
  },
  output: {
    path: "./src/api/generated",
    barrel: { type: "named" },
  },
  plugins: [
    pluginOas({
      validate: true,
    }),
    pluginTs({
      output: {
        path: "models",
        barrel: { type: "named" },
        banner: generatedBanner,
        override: true,
      },
      dateType: "string",
      enumType: "literal",
      paramsCasing: "camelcase",
      unknownType: "unknown",
    }),
    pluginClient({
      output: {
        path: "client",
        barrel: { type: "named" },
        banner: generatedBanner,
        override: true,
      },
      bundle: true,
      client: "axios",
      dataReturnType: "data",
      paramsCasing: "camelcase",
      paramsType: "object",
      pathParamsType: "object",
    }),
  ],
});
