/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//agents'
      | '//projects'
      | '//projects/[project]'
      | '//tasks'
    >,
    '//agents': RouteRecordInfo<
      '//agents',
      '/agents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//projects': RouteRecordInfo<
      '//projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | '//projects/[project]'
    >,
    '//projects/[project]': RouteRecordInfo<
      '//projects/[project]',
      '/projects/:project',
      { project: ParamValue<true> },
      { project: ParamValue<false> },
      | never
    >,
    '//tasks': RouteRecordInfo<
      '//tasks',
      '/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//agents'
        | '//projects'
        | '//projects/[project]'
        | '//tasks'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/agents.vue': {
      routes:
        | '//agents'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/projects.vue': {
      routes:
        | '//projects'
        | '//projects/[project]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/projects/[project].vue': {
      routes:
        | '//projects/[project]'
      views:
        | never
      pathParamNames:
        | 'project'
    }
    'src/pages/index/tasks.vue': {
      routes:
        | '//tasks'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
